In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array(([1,2,4],[3,4,5]))

array([[1, 2, 4],
       [3, 4, 5]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.empty((5,5))

array([[4.66369108e-310, 0.00000000e+000, 1.34832279e-094,
        8.73990398e+245, 9.11573821e-304],
       [2.41441018e-310, 9.00691034e-313, 2.10149145e+251,
        1.42608500e+248, 3.76603666e-085],
       [2.28354978e+243, 1.32921007e-311, 5.81499259e+252,
        1.87255730e-311, 2.21525978e+214],
       [1.33360291e+241, 2.41440681e-310, 4.31912682e-239,
        3.06528923e-313, 1.68400738e-019],
       [6.95572870e-245, 2.64171898e-313, 5.48094825e-294,
        7.79689286e-315, 1.02765654e-321]])

In [10]:
np.empty(10)

array([4.66369110e-310, 0.00000000e+000, 2.41907520e-312, 2.44029516e-312,
       8.48798317e-313, 9.33678148e-313, 8.70018275e-313, 1.32650015e-269,
       4.97626403e-270, 8.34456596e-308])

In [11]:
np.empty(10,dtype=np.int64)

array([    94394158707296,                  0,       489626271845,
             493921239151,       171798691880,       188978561077,
             176093659188, 584350864924213289, 577876983679485956,
        12948394397863940])

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
np.arange(11,0,-2)

array([11,  9,  7,  5,  3,  1])

In [16]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])

In [17]:
a=np.empty(11)

In [18]:
a

array([4.66369142e-310, 0.00000000e+000, 2.05833592e-312, 2.18565567e-312,
       8.48798317e-313, 1.03977794e-312, 1.01855798e-312, 9.54898106e-313,
       8.70018275e-313, 5.04621361e+180, 7.49779533e+247])

In [19]:
np.sort(a)

array([0.00000000e+000, 8.48798317e-313, 8.70018275e-313, 9.54898106e-313,
       1.01855798e-312, 1.03977794e-312, 2.05833592e-312, 2.18565567e-312,
       4.66369142e-310, 5.04621361e+180, 7.49779533e+247])

In [20]:
b=np.array([435,542,24452,13,11412,5235,23345,2354,2335,57545,74])

In [21]:
b

array([  435,   542, 24452,    13, 11412,  5235, 23345,  2354,  2335,
       57545,    74])

In [22]:
np.sort(b)

array([   13,    74,   435,   542,  2335,  2354,  5235, 11412, 23345,
       24452, 57545])

In [23]:
np.concatenate((a,b))

array([4.66369142e-310, 0.00000000e+000, 2.05833592e-312, 2.18565567e-312,
       8.48798317e-313, 1.03977794e-312, 1.01855798e-312, 9.54898106e-313,
       8.70018275e-313, 5.04621361e+180, 7.49779533e+247, 4.35000000e+002,
       5.42000000e+002, 2.44520000e+004, 1.30000000e+001, 1.14120000e+004,
       5.23500000e+003, 2.33450000e+004, 2.35400000e+003, 2.33500000e+003,
       5.75450000e+004, 7.40000000e+001])

In [24]:
a = np.array([5, 6, 7, 8])

In [25]:
np.concatenate((a,b))

array([    5,     6,     7,     8,   435,   542, 24452,    13, 11412,
        5235, 23345,  2354,  2335, 57545,    74])

In [26]:
np.sort(np.concatenate((a,b)))

array([    5,     6,     7,     8,    13,    74,   435,   542,  2335,
        2354,  5235, 11412, 23345, 24452, 57545])

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7, 8]])

In [28]:
z=np.concatenate((x,y))
z1=np.concatenate((x,y),axis=1)
z2=np.concatenate((x,y),axis=None)

In [29]:
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
z1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [31]:
z2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
z.ndim

2

In [33]:
z.size

8

In [34]:
z.shape

(4, 2)

In [35]:
x.shape

(2, 2)

In [36]:
y.ndim

2

In [37]:
b.ndim

1

In [38]:
aa=np.array([1,2,3,4])
ab=np.array([5,6,7,8])
ac=np.concatenate((aa,ab))
ac

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
aa.shape

(4,)

In [40]:
aa.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [41]:
aa.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [42]:
ad=np.arange(1,26)

In [43]:
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [44]:
a55=ad.reshape(5,5)

In [45]:
a55

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
a=np.arange(1,11)

In [47]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a.shape

(10,)

In [49]:
ar=a[np.newaxis,:]
ac=a[:,np.newaxis]

In [50]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [51]:
ac

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [52]:
ar.shape

(1, 10)

In [53]:
ac.shape

(10, 1)

In [54]:
chess_board=np.zeros((8,8),dtype=int)
chess_board[0::2,0::2]=1
chess_board[1::2,1::2]=1

In [55]:
chess_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [56]:
amax=np.array([1,5,7,9])
bmax=np.array([2,4,8,3])

In [57]:
np.maximum(amax,bmax)

array([2, 5, 8, 9])

In [58]:
np.where(bmax<4,"small","big")

array(['small', 'big', 'big', 'small'], dtype='<U5')

In [59]:
amax.cumsum()

array([ 1,  6, 13, 22])

In [60]:
np.cumsum(np.array([3,4,5,32]))

array([ 3,  7, 12, 44])

In [61]:
amax.mean()

5.5

In [62]:
amax.cumprod()

array([  1,   5,  35, 315])

In [63]:
35*9

315

In [64]:
aTrue=bmax>3

In [65]:
aTrue

array([False,  True,  True, False])

In [66]:
aTrue.sum()

2

In [67]:
aTrue.all()

False

In [68]:
aTrue.any()

True

In [69]:
unique=np.array([1,4,3,5,4,4,2,5,9])

In [70]:
np.unique(unique)

array([1, 2, 3, 4, 5, 9])

In [71]:
np.save('saveamax',amax)

In [72]:
np.savez('saveabmax',asave=amax,bsave=bmax)

In [73]:
np.load('saveamax.npy')

array([1, 5, 7, 9])

In [74]:
loadabmax=np.load('saveabmax.npz')

In [75]:
loadabmax['asave']

array([1, 5, 7, 9])

In [76]:
loadabmax['bsave']

array([2, 4, 8, 3])

In [77]:
np.split(unique,[2,6])

[array([1, 4]), array([3, 5, 4, 4]), array([2, 5, 9])]

In [78]:
np.repeat(amax,4)

array([1, 1, 1, 1, 5, 5, 5, 5, 7, 7, 7, 7, 9, 9, 9, 9])

In [79]:
np.tile(amax,4)

array([1, 5, 7, 9, 1, 5, 7, 9, 1, 5, 7, 9, 1, 5, 7, 9])

In [80]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [81]:
print(ar>5)

[[False False False False False  True  True  True  True  True]]


In [82]:
five_up=ar[ar>5]

In [83]:
print(five_up)

[ 6  7  8  9 10]


In [84]:
five_up

array([ 6,  7,  8,  9, 10])

In [85]:
a55

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
a13up=a55[a55>13]
print(a13up)

[14 15 16 17 18 19 20 21 22 23 24 25]


In [87]:
a55[a55>13]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [88]:
a55>13

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [89]:
adiv2=a55[a55%2==0]
adiv2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [90]:
a55[(a55>=10)&(a55<=20)]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [91]:
a55non0=np.nonzero((a55>7) & (a55<22))
a55non0

(array([1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4]),
 array([2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0]))

In [92]:
a55[a55non0]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [93]:
list_of_coordinates= list(zip(a55non0[0], a55non0[1]))
for coordi in list_of_coordinates:
     print(coordi)

(1, 2)
(1, 3)
(1, 4)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(4, 0)


In [99]:
non0=np.array(([0,1,0],[9,0,9]))
non0

array([[0, 1, 0],
       [9, 0, 9]])

In [100]:
non0[non0.nonzero()]

array([1, 9, 9])

In [101]:
non0.nonzero()

(array([0, 1, 1]), array([1, 0, 2]))