In [136]:
import numpy as np

In [137]:
np.array([1,2,3])

array([1, 2, 3])

In [138]:
np.array(([1,2,4],[3,4,5]))

array([[1, 2, 4],
       [3, 4, 5]])

In [139]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [140]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [142]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [143]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [144]:
np.empty((5,5))

array([[5.e-324, 0.e+000, 5.e-324, 0.e+000, 5.e-324],
       [0.e+000, 5.e-324, 0.e+000, 5.e-324, 0.e+000],
       [5.e-324, 0.e+000, 5.e-324, 0.e+000, 5.e-324],
       [0.e+000, 5.e-324, 0.e+000, 5.e-324, 0.e+000],
       [5.e-324, 0.e+000, 5.e-324, 0.e+000, 5.e-324]])

In [145]:
np.empty(10)

array([4.66369117e-310, 0.00000000e+000, 3.95252517e-323, 4.44659081e-323,
       6.42285340e-323, 6.91691904e-323, 8.89318163e-323, 9.38724727e-323,
       1.13635099e-322, 1.18575755e-322])

In [146]:
np.empty(10,dtype=np.int64)

array([94394160229904,              0,              8,              9,
                   13,             14,             18,             19,
                   23,             24])

In [147]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [150]:
np.arange(11,0,-2)

array([11,  9,  7,  5,  3,  1])

In [151]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])

In [152]:
a=np.empty(11)

In [153]:
a

array([4.66369150e-310, 0.00000000e+000, 2.33419537e-312, 2.37663529e-312,
       2.10077583e-312, 8.48798317e-313, 9.33678148e-313, 1.03977794e-312,
       1.20953760e-312, 2.25369106e+184, 5.01163106e+217])

In [154]:
np.sort(a)

array([0.00000000e+000, 8.48798317e-313, 9.33678148e-313, 1.03977794e-312,
       1.20953760e-312, 2.10077583e-312, 2.33419537e-312, 2.37663529e-312,
       4.66369150e-310, 2.25369106e+184, 5.01163106e+217])

In [155]:
b=np.array([435,542,24452,13,11412,5235,23345,2354,2335,57545,74])

In [156]:
b

array([  435,   542, 24452,    13, 11412,  5235, 23345,  2354,  2335,
       57545,    74])

In [157]:
np.sort(b)

array([   13,    74,   435,   542,  2335,  2354,  5235, 11412, 23345,
       24452, 57545])

In [158]:
np.concatenate((a,b))

array([4.66369150e-310, 0.00000000e+000, 2.33419537e-312, 2.37663529e-312,
       2.10077583e-312, 8.48798317e-313, 9.33678148e-313, 1.03977794e-312,
       1.20953760e-312, 2.25369106e+184, 5.01163106e+217, 4.35000000e+002,
       5.42000000e+002, 2.44520000e+004, 1.30000000e+001, 1.14120000e+004,
       5.23500000e+003, 2.33450000e+004, 2.35400000e+003, 2.33500000e+003,
       5.75450000e+004, 7.40000000e+001])

In [159]:
a = np.array([5, 6, 7, 8])

In [160]:
np.concatenate((a,b))

array([    5,     6,     7,     8,   435,   542, 24452,    13, 11412,
        5235, 23345,  2354,  2335, 57545,    74])

In [161]:
np.sort(np.concatenate((a,b)))

array([    5,     6,     7,     8,    13,    74,   435,   542,  2335,
        2354,  5235, 11412, 23345, 24452, 57545])

In [162]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7, 8]])

In [163]:
z=np.concatenate((x,y))
z1=np.concatenate((x,y),axis=1)
z2=np.concatenate((x,y),axis=None)

In [164]:
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [165]:
z1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [166]:
z2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [167]:
z.ndim

2

In [168]:
z.size

8

In [169]:
z.shape

(4, 2)

In [170]:
x.shape

(2, 2)

In [171]:
y.ndim

2

In [172]:
b.ndim

1

In [173]:
aa=np.array([1,2,3,4])
ab=np.array([5,6,7,8])
ac=np.concatenate((aa,ab))
ac

array([1, 2, 3, 4, 5, 6, 7, 8])

In [174]:
aa.shape

(4,)

In [175]:
aa.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [176]:
aa.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [177]:
ad=np.arange(1,26)

In [178]:
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [179]:
a55=ad.reshape(5,5)

In [180]:
a55

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [181]:
a=np.arange(1,11)

In [182]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
a.shape

(10,)

In [184]:
ar=a[np.newaxis,:]
ac=a[:,np.newaxis]

In [185]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [186]:
ac

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [187]:
ar.shape

(1, 10)

In [188]:
ac.shape

(10, 1)

In [189]:
chess_board=np.zeros((8,8),dtype=int)
chess_board[0::2,0::2]=1
chess_board[1::2,1::2]=1

In [190]:
chess_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [191]:
amax=np.array([1,5,7,9])
bmax=np.array([2,4,8,3])

In [192]:
np.maximum(amax,bmax)

array([2, 5, 8, 9])

In [193]:
np.where(bmax<4,"small","big")

array(['small', 'big', 'big', 'small'], dtype='<U5')

In [194]:
amax.cumsum()

array([ 1,  6, 13, 22])

In [195]:
np.cumsum(np.array([3,4,5,32]))

array([ 3,  7, 12, 44])

In [196]:
amax.mean()

5.5

In [197]:
amax.cumprod()

array([  1,   5,  35, 315])

In [198]:
35*9

315

In [199]:
aTrue=bmax>3

In [200]:
aTrue

array([False,  True,  True, False])

In [201]:
aTrue.sum()

2

In [202]:
aTrue.all()

False

In [203]:
aTrue.any()

True

In [271]:
unique=np.array([1,4,3,5,4,4,2,5,3])

In [272]:
np.unique(unique)

array([1, 2, 3, 4, 5])

In [273]:
np.unique(unique, return_index=True)

(array([1, 2, 3, 4, 5]), array([0, 6, 2, 1, 3]))

In [274]:
uniquenumb,uniqueind=np.unique(unique,return_index=True)
uniquenumb1,uniquecount=np.unique(unique,return_counts=True)

In [275]:
uniquenumb

array([1, 2, 3, 4, 5])

In [276]:
uniqueind

array([0, 6, 2, 1, 3])

In [277]:
uniquecount

array([1, 1, 2, 3, 2])

In [206]:
np.save('saveamax',amax)

In [207]:
np.savez('saveabmax',asave=amax,bsave=bmax)

In [208]:
np.load('saveamax.npy')

array([1, 5, 7, 9])

In [209]:
loadabmax=np.load('saveabmax.npz')

In [210]:
loadabmax['asave']

array([1, 5, 7, 9])

In [211]:
loadabmax['bsave']

array([2, 4, 8, 3])

In [212]:
np.split(unique,[2,6])

[array([1, 4]), array([3, 5, 4, 4]), array([2, 5, 9])]

In [213]:
np.repeat(amax,4)

array([1, 1, 1, 1, 5, 5, 5, 5, 7, 7, 7, 7, 9, 9, 9, 9])

In [214]:
np.tile(amax,4)

array([1, 5, 7, 9, 1, 5, 7, 9, 1, 5, 7, 9, 1, 5, 7, 9])

In [215]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [216]:
print(ar>5)

[[False False False False False  True  True  True  True  True]]


In [217]:
five_up=ar[ar>5]

In [218]:
print(five_up)

[ 6  7  8  9 10]


In [219]:
five_up

array([ 6,  7,  8,  9, 10])

In [220]:
a55

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [221]:
a13up=a55[a55>13]
print(a13up)

[14 15 16 17 18 19 20 21 22 23 24 25]


In [222]:
a55[a55>13]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [223]:
a55>13

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [224]:
adiv2=a55[a55%2==0]
adiv2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [225]:
a55[(a55>=10)&(a55<=20)]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [226]:
a55non0=np.nonzero((a55>7) & (a55<22))
a55non0

(array([1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4]),
 array([2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0]))

In [227]:
a55[a55non0]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [228]:
list_of_coordinates= list(zip(a55non0[0], a55non0[1]))
for coordi in list_of_coordinates:
     print(coordi)

(1, 2)
(1, 3)
(1, 4)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(4, 0)


In [229]:
non0=np.array(([0,1,0],[9,0,9]))
non0

array([[0, 1, 0],
       [9, 0, 9]])

In [230]:
non0[non0.nonzero()]

array([1, 9, 9])

In [231]:
non0.nonzero()

(array([0, 1, 1]), array([1, 0, 2]))

In [232]:
a01 = np.array([[1,1],[2,2]])
b01 = np.array([[3,3],[4,4]])

In [233]:
np.concatenate((a01,b01))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [234]:
np.vstack((a01,b01))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [235]:
np.hstack((a01,b01))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [236]:
np.hsplit(a55,(3,5))

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18],
        [21, 22, 23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]]),
 array([], shape=(5, 0), dtype=int64)]

In [237]:
np.hsplit(a55,(2,4))

[array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]])]

In [238]:
aabb = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = aabb[0, :]
b1[0] = 99

In [239]:
b1

array([99,  2,  3,  4])

In [240]:
aabb

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [241]:
aabb[0:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [249]:
m1=np.array([[1,2,3],[1,1,1]])
m2=np.array([[2],[3]])
m1*m2

array([[2, 4, 6],
       [3, 3, 3]])

In [254]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])