In [6]:
import numpy as np

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [42]:
np.array(([1,2,4],[3,4,5]))

array([[1, 2, 4],
       [3, 4, 5]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.empty((5,5))

array([[ 4.64397182e-310,  0.00000000e+000,  3.82363814e-301,
         3.82546092e-301,  3.82728370e-301],
       [ 3.82910648e-301,  3.83092926e-301,  3.83275205e-301,
         3.83457483e-301,  3.83639761e-301],
       [ 3.83822039e-301,  3.84004317e-301,  3.84186595e-301,
         3.84368873e-301,  3.84551151e-301],
       [ 3.84733429e-301,  3.84915707e-301,  3.85097985e-301,
         3.85280263e-301,  3.85462541e-301],
       [-7.05369267e-278,  1.29024128e-263, -1.98543874e-263,
        -1.30117664e-258,  1.02765654e-321]])

In [14]:
np.empty(10)

array([4.64397198e-310, 0.00000000e+000, 6.92081990e-310, 3.21142670e-322,
       4.64397196e-310, 6.92082231e-310, 6.92081990e-310, 6.92082145e-310,
       6.92081990e-310, 6.92082145e-310])

In [15]:
np.empty(10,dtype=np.int64)

array([ 93995039221296,               0, 140078954312624,              65,
        93995038821920, 140079003102416, 140078954312496, 140078985521648,
       140078954312432, 140078985521648])

In [16]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [45]:
np.arange(11,0,-2)

array([11,  9,  7,  5,  3,  1])

In [20]:
np.linspace(1,11,9)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ,  7.25,  8.5 ,  9.75, 11.  ])

In [21]:
a=np.empty(11)

In [22]:
a

array([4.64397214e-310, 0.00000000e+000, 2.33419537e-312, 2.37663529e-312,
       2.10077583e-312, 8.48798317e-313, 9.33678148e-313, 1.03977794e-312,
       1.20953760e-312, 2.61354237e-306, 4.74303020e-322])

In [23]:
np.sort(a)

array([0.00000000e+000, 4.74303020e-322, 8.48798317e-313, 9.33678148e-313,
       1.03977794e-312, 1.20953760e-312, 2.10077583e-312, 2.33419537e-312,
       2.37663529e-312, 4.64397214e-310, 2.61354237e-306])

In [24]:
b=np.array([435,542,24452,13,11412,5235,23345,2354,2335,57545,74])

In [25]:
b

array([  435,   542, 24452,    13, 11412,  5235, 23345,  2354,  2335,
       57545,    74])

In [26]:
np.sort(b)

array([   13,    74,   435,   542,  2335,  2354,  5235, 11412, 23345,
       24452, 57545])

In [27]:
np.concatenate((a,b))

array([4.64397214e-310, 0.00000000e+000, 2.33419537e-312, 2.37663529e-312,
       2.10077583e-312, 8.48798317e-313, 9.33678148e-313, 1.03977794e-312,
       1.20953760e-312, 2.61354237e-306, 4.74303020e-322, 4.35000000e+002,
       5.42000000e+002, 2.44520000e+004, 1.30000000e+001, 1.14120000e+004,
       5.23500000e+003, 2.33450000e+004, 2.35400000e+003, 2.33500000e+003,
       5.75450000e+004, 7.40000000e+001])

In [28]:
a = np.array([5, 6, 7, 8])

In [29]:
np.concatenate((a,b))

array([    5,     6,     7,     8,   435,   542, 24452,    13, 11412,
        5235, 23345,  2354,  2335, 57545,    74])

In [30]:
np.sort(np.concatenate((a,b)))

array([    5,     6,     7,     8,    13,    74,   435,   542,  2335,
        2354,  5235, 11412, 23345, 24452, 57545])

In [64]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7, 8]])

In [65]:
z=np.concatenate((x,y))
z1=np.concatenate((x,y),axis=1)
z2=np.concatenate((x,y),axis=None)

In [66]:
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
z1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [68]:
z2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
z.ndim

2

In [35]:
z.size

8

In [36]:
z.shape

(4, 2)

In [77]:
x.shape

(2, 2)

In [38]:
y.ndim

2

In [39]:
b.ndim

1

In [99]:
aa=np.array([1,2,3,4])
ab=np.array([5,6,7,8])
ac=np.concatenate((aa,ab))
ac

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
aa.shape

(4,)

In [101]:
aa.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [102]:
aa.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [87]:
ad=np.arange(1,26)

In [88]:
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [89]:
ad.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
a=np.arange(1,11)

In [93]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
a.shape

(10,)

In [108]:
ar=a[np.newaxis,:]
ac=a[:,np.newaxis]

In [109]:
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [110]:
ac

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [111]:
ar.shape

(1, 10)

In [112]:
ac.shape

(10, 1)

In [235]:
chess_board=np.zeros((8,8),dtype=int)
chess_board[0::2,0::2]=1
chess_board[1::2,1::2]=1

In [237]:
chess_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [240]:
amax=np.array([1,5,7,9])
bmax=np.array([2,4,8,3])

In [242]:
np.maximum(amax,bmax)

array([2, 5, 8, 9])

In [245]:
np.where(bmax<4,"small","big")

array(['small', 'big', 'big', 'small'], dtype='<U5')

In [247]:
amax.cumsum()

array([ 1,  6, 13, 22])

In [248]:
np.cumsum(np.array([3,4,5,32]))

array([ 3,  7, 12, 44])

In [249]:
amax.mean()

5.5

In [250]:
amax.cumprod()

array([  1,   5,  35, 315])

In [252]:
35*9

315

In [255]:
aTrue=bmax>3

In [256]:
aTrue

array([False,  True,  True, False])

In [257]:
aTrue.sum()

2

In [258]:
aTrue.all()

False

In [260]:
aTrue.any()

True

In [263]:
unique=np.array([1,4,3,5,4,4,2,5,9])

In [264]:
np.unique(unique)

array([1, 2, 3, 4, 5, 9])